// SPDX-License-Identifier: SSPL-1.0
// Copyright (c) 2023-present Banca d'Italia

/*  _   __        __                 __
 * | | / /__ ____/ /__ ________  ___/ /__
 * | |/ / _ `/ _  / _ `/ __/ _ \/ _  / -_)
 * |___/\_,_/\_,_/\_,_/\__/\___/\_,_/\__/
 *
 * @file Script to generate the diagnostic codes documentation page.
 */

import { DIAGNOSTIC_MESSAGES } from '../src/datalogpm/diagnostic-messages';

const errorPageHeader = `
= Diagnostic codes
:tags: compiler, errors, troubleshooting
:description: Documentation for compiler code errors, including error codes, descriptions, causes, and solutions.

// ATTENTION: This file is auto-generated. Do not edit it directly.
// Generated by \`npm run diagnostic-codes\` in server package.

This page provides a comprehensive reference for the diagnostic codes emitted by Vadacode. 
Each diagnostic code is associated with a specific severity level that may occur during program analysis.

`;

const errorPageFooter = `
`;

const diagnosticMessages = DIAGNOSTIC_MESSAGES;

// Open file for writing
import * as fs from 'fs';
import * as path from 'path';
import { DiagnosticSeverity } from 'vscode-languageserver';

let errorSection = ''; 
for (const [code, diagnostic] of Object.entries(diagnosticMessages)) {

	let section = `
[#[ERROR_CODE]]
== [ERROR_SEVERITY_ICON] _[ERROR_NAME]_ (\`[ERROR_CODE]\`)
[ERROR_SEVERITY].

[.excerpt]
____
[ERROR_MESSAGE]
____

`
.replace(/\[ERROR_NAME\]/g, diagnostic.name)
.replace(/\[ERROR_CODE\]/g, diagnostic.code)
.replace(/\[ERROR_MESSAGE\]/g, diagnostic.message.replace(/\{/g, '\\{'))
.replace(/\[ERROR_SEVERITY_ICON\]/g, getIconFromDiagnosticSeverity(diagnostic.severity))
.replace(/\[ERROR_SEVERITY\]/g, getSeverityFromDiagnosticSeverity(diagnostic.severity));

	if (diagnostic.description) {
		section += `
=== Description
[ERROR_DESCRIPTION]
`.replace(/\[ERROR_DESCRIPTION\]/g, diagnostic.description);
	}

	if (diagnostic.examples) {
		for (const index in diagnostic.examples) {
			const example = diagnostic.examples[index];
			const fix = diagnostic.fixes ? diagnostic.fixes[index] : null;

			section += `
=== Example
[source,datalogpm]
----
[BROKEN_CODE]
----
`.replace(/\[BROKEN_CODE\]/g, example);

			if (fix) {
				section += `
=== Fix
[source,datalogpm]
----
[FIXED_CODE]
----
`.replace(/\[FIXED_CODE\]/g, fix);
			}
		}

		if (diagnostic.notes) {
			for (const note of diagnostic.notes) {
				let admonition = 'NOTE';
				switch(note.type) {
					case 'caution':
						admonition = 'CAUTION';
						break;
					case 'tip':
						admonition = 'TIP';
						break;
					case 'warning':
						admonition = 'WARNING';
						break;
					case 'important':
						admonition = 'IMPORTANT';	
						break;
				}

				section += `
${admonition}: ${note.value}
`;
			}
		}
			
	}


	errorSection += section;
}

const page = errorPageHeader + errorSection + errorPageFooter;

const outputDir = path.join(__dirname, "..", "..", 'docs', 'manual', 'modules', 'ROOT', 'pages', );
const outputFile = path.join(outputDir, 'diagnostic-codes.adoc');
// Write the page to a file
fs.writeFileSync(outputFile, page, 'utf8');


function getIconFromDiagnosticSeverity(diagnosticSeverity: DiagnosticSeverity): string {
	switch (diagnosticSeverity) {
		case DiagnosticSeverity.Error:
			return '❌';
		case DiagnosticSeverity.Warning:
			return '⚠️';
		case DiagnosticSeverity.Information:
			return 'ℹ️';
		case DiagnosticSeverity.Hint:
			return '💡';
		default:
			return 'Unknown';
	}
}

function getSeverityFromDiagnosticSeverity(diagnosticSeverity: DiagnosticSeverity): string {
	switch (diagnosticSeverity) {
		case DiagnosticSeverity.Error:
			return 'Error';
		case DiagnosticSeverity.Warning:
			return 'Warning';
		case DiagnosticSeverity.Information:
			return 'Information';
		case DiagnosticSeverity.Hint:
			return 'Hint';
		default:
			return 'Unknown';
	}
}
